
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer self-update
    - composer install
    - pear config-set auto_discover 1
    - pear channel-update pear.php.net
    - pear install PHP_CodeSniffer
    - phpenv rehash

before_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;

script:
    - phpunit
    - phpcs
    - php bin/validate-coverage

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z